name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 5000:5000

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        if [ -f tests/test_app.py ]; then
          python3 -m unittest discover -s tests
        else
          echo "No test files found"
        fi

    - name: Run Flask Server (Background)
      run: |
        nohup flask run --host=0.0.0.0 &
        sleep 5

    - name: UI Smoke Test with Curl
      run: |
        curl --fail http://127.0.0.1:5000 || exit 1
        curl --fail http://127.0.0.1:5000/result || echo "No result route"

    - name: Check for Known Vulnerabilities
      run: |
        pip install safety
        safety check
